### ISSUE TITLE
Truncated output when reading data not readily available

### ISSUE THREAD

**Issue by bendem** [exceptionfactory/jagged#1]
I've been trying to pinpoint a weird behaviour I have with this library.

If I decrypt a file from disk it works fine using the example in the README (had to dig up your copy implementation which I found on your blog).

If I decrypt a file I get on the fly from the network (from an s3 bucket in my case), the output is truncated leading either to 0 length decrypted files or truncated files.

I've pinpointed this to a weird behaviour I'm seeing here : https://github.com/exceptionfactory/jagged/blob/6080163015d71c0c8fbc93895f683b9085c6092b/jagged-framework/src/main/java/com/exceptionfactory/jagged/framework/stream/DecryptingChannel.java#L110-L115

if `readPlainBuffer` returns `-1`, the content read in previous iterations of the loop is thrown away and `read` is set to EOF, basically ignoring all the data that's been read so far, BUT, that data has been written into the `outputBuffer`, thus the caller's `ByteBuffer` has changed but the method returns that it hasn't.

My guess is that you tested with files small enough to not cause read(buffer) to fill the buffer, but when reading from the network, things work slightly differently (buffers are not always filled up, read can return 0 in some cases, etc.).

The code is complex and I might be misunderstanding what's happening, for now, I've replaced jagged with a stream that passes data to the `age` binary using ProcessBuilder and everything works (pointing to jagged doing something wrong).

**Comment by exceptionfactory** [comment]
Thanks for raising this issue and the describing the situation @bendem.

You are correct that the behavior would be different when reading from a network channel, and that the read call may not always return data, requiring multiple iterations.

The issue seems to be related to the fact that when the `DecryptingChannel` receives an EOF, it returns an EOF, instead of saving that state and returning the number of bytes read. Adjusting to the behavior would probably resolve the issue, so this is a helpful prompt for a closer evaluation.

Are you able to provide a code snippet that references the reading from the `DecryptingChannel`?

**Comment by bendem** [comment]
I can't provide a fully reproducible case right now, the case happens with the aws s3 sdk:

```java
try (
    ResponseInputStream<GetObjectResponse> object = s3.getObject(builder -> builder
        .bucket(bucket)
        .key(key));
    ReadableByteChannel ageChannel = channelFactory.newDecryptingChannel(
        Channels.newChannel(object),
        Collections.singletonList(stanzaReader));
    HashingStream hashingStream = new HashingStream("SHA256", Channels.newInputStream(ageChannel))
) {
    hashingStream.transferTo(outputStream);
}
```

I'll see later this week if I can isolate it to present a reproducible test case for you.

**Comment by exceptionfactory** [comment]
Thanks for the reply and code snippet, that is helpful. If you have a reference to the code for `HashingStream` in particular, that would be helpful. The wrapping of `Channels.newInputStream()` is a useful pointer. I plan to take a closer look at this soon.

**Comment by exceptionfactory** [comment]
@bendem I put together pull request #2 adjusting the behavior of `DecryptingChannel.read()` to return the number of bytes read into the provided `ByteBuffer` before returning `-1` prematurely. The updated unit test provides some verification of the behavior, but if you are able to pull the branch and try the changes, that would be a helpful confirmation.

**Comment by exceptionfactory** [comment]
> The code looks fine, I'll be sure to try and test this tomorrow if I can get everything to build locally.

Thanks @bendem! Glad to release a new version once you are able to evaluate the changes.
